### ISSUE TITLE
Wrong guide link in README

### ISSUE THREAD

**Issue by LouChao98** [zqtan1024/sequence-to-set#1]
The link to the guide [https://radimrehurek.com/gensim/scripts/glove2word2vec.html]() in section Pretrained Wordvecs is wrong. Your instruction is word2vec2glove but the link is glove2word2vec.

I guess the proper commands are
```python
from gensim.models import KeyedVectors

kv = KeyedVectors.load_word2vec_format('PubMed-shuffle-win-30.bin', binary=True)
kv.save_word2vec_format('PubMed-shuffle-win-30.txt', write_header=True)
```

After checking https://github.com/zqtan1024/sequence-to-set/blob/b50d3ec03bce37886c6bcacad24772939836b526/ssn/input_reader.py#L172-L185 I think "GloVe format" is not what you expected, because code will skip the first line. I think the conversion is from a binary word2vec format file to a word2vec format text file,

**Comment by zqtan1024** [comment]
Thank you very much! We have fixed this bug in the README.
