### ISSUE TITLE
Questions about inputs

### ISSUE THREAD

**Issue by LouChao98** [zqtan1024/sequence-to-set#3]
Hello again,
I would like to know more about your code's details. I have two questions
1. The data format in README contains "ltokens" and "rtokens", and they are used to construct documents in your `input_reader.py`. I guess they are context of current sentences,or "tokens" in README. Then the question is do you use context information? 
2. You use POS tag as input features, but it is not contained in the original ACE2005. Do I miss the annotation? Or you use a pos tagger to label datasets.

**Comment by zqtan1024** [comment]
1. Yes, the 'ltokens' contains the tokens from the previous sentence and the 'rtokens' contains the tokens from the next sentence.
2. We use 'spacy' [spacy.load("en_core_web_sm")] to get the POS tags. By the way, the POS tags are not that important.

**Comment by LouChao98** [comment]
I run experiments to compare models with/without context and with/without pos using the GENIA provided in README. 
Scores are micro f1 of **one run** on genia_test_context.json.
1. +context +pos 79.92
2. -context +pos 79.58
3. -context -pos 79.35

Can you verify my results?  

Specifically, "-context" is implemented by change https://github.com/zqtan1024/sequence-to-set/blob/baa44feffcbc8846c6774cd6cc839062c6115ce8/ssn/input_reader.py#L198-L199 to 
```
ltokens = []
rtokens = []
```

For "-pos", I just set "use_pos = false" in example.conf.

Correct me please if I am wrong.

**Comment by zqtan1024** [comment]
Your settings are correct! You can try a bigger epoch (60 or 100) to get better results!
