### ISSUE TITLE
Would you mind supply ACE04,ACE05 preprocessing code?

### ISSUE THREAD

**Issue by SCAUapc** [zqtan1024/sequence-to-set#4]
Hi ! Your work is amazing! Now I am doing some research on nested-ner. Would you mind supply the ACE dataset preprocess code? And can you give some advice about preprocessing? I wanna know how you tokenize sentences and words.

**Comment by zqtan1024** [comment]
We use BERT-MRC (https://github.com/ShannonAI/mrc-for-flat-nested-ner/blob/master/ner2mrc/download.md) datasets. Only BERT's original tokenizer is used in the sentence tokenization process. In addition, we use contextual sentences (left and right), which you can construct based on the genia dataset format.

**Comment by SCAUapc** [comment]
> Thanks for your reply! 
If only use BERT's original tokenizer, how can I get the pos and word(to use Glove)? I think the pos and the word(Glove) may not be aligned to the tokens(by BERT's original tokenizer)

**Comment by SCAUapc** [comment]
> We use BERT-MRC (https://github.com/ShannonAI/mrc-for-flat-nested-ner/blob/master/ner2mrc/download.md) datasets. Only BERT's original tokenizer is used in the sentence tokenization process. In addition, we use contextual sentences (left and right), which you can construct based on the genia dataset format.

Thanks for your reply!
If only use BERT's original tokenizer, how can I get the pos and word(to use Glove)? I think the pos and the word(Glove) may not be aligned to the tokens(by BERT's original tokenizer)

**Comment by zqtan1024** [comment]
You can refer to #3 to obtain pos. For more information on how to align, please refer to our code (https://github.com/zqtan1024/sequence-to-set/blob/baa44feffcbc8846c6774cd6cc839062c6115ce8/ssn/models.py#L180).

**Comment by SCAUapc** [comment]
> You can refer to #3 to obtain pos. For more information on how to align, please refer to our code (
> 
> https://github.com/zqtan1024/sequence-to-set/blob/baa44feffcbc8846c6774cd6cc839062c6115ce8/ssn/models.py#L180
> 
> ).

ver thanks for your reply!
Are below steps correct?
Firstly, cut article to sentence. Secondly, use BertTokenzier to cut sentece get word (this word use glove embedding and bert embedding). Meanwhile, for sentence, use spacy to get POS. 

Would you mind addind my wechat(377907962)? It is my pleasure if I can make friend with you.
