### ISSUE TITLE
ltokens和rtokens问题

### ISSUE THREAD

**Issue by z1ouhan** [zqtan1024/sequence-to-set#7]
请问这两个数是如何构造的呢？genia_train_dev_context大部分词语为啥没有rtokens呢，难道不是下一句的tokens吗？
希望能够解惑！谢谢！

**Comment by zqtan1024** [comment]
是按照上一句和下一句来构造的。但有些句子在实验中会超过bert最大输入长度的限制，简便起见，只保留了ltokens。
